### ISSUE TITLE
[_openmp_mutex] How to enforce GNU OpenMP?

### ISSUE THREAD

**Issue by pearu** [conda-forge/ctng-compilers-feedstock#49]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
While [Switching OpenMP implementation](https://conda-forge.org/docs/maintainer/knowledge_base.html#switching-openmp-implementation) advocates using `conda install _openmp_mutex=*=*_gnu`, this leads to
```
UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (_openmp_mutex):

  - _openmp_mutex[build=*_gnu]
```

To reproduce, create an environment using pytorch-cuda-dev.yaml file (see below), activate, and run `conda install _openmp_mutex=*=*_gnu`.

I also tried inserting `_openmp_mutex=*=*_gnu` to the yaml with no success.

What seems to work is a manual reset of the `libgomp.so.1->libomp.so` link to `libgomp.so.1->libgomp.so`:
```
$ ln -fs $CONDA_PREFIX/lib/libgomp.so $CONDA_PREFIX/lib/libgomp.so.1
```
but that is obviously not a sustainable solution.

<br/>
<code>pytorch-cuda-dev.yaml</code>:
<details>

```
name: pytorch-cuda-dev
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3
  - numpy
  - ninja
  - pyyaml
  - mkl
  - mkl-include
  - setuptools
  - cmake
  - cffi
  - typing
  - pytest
  - compilers
  - flake8
  - psutil
  - hypothesis
  - nvcc_linux-64=11.0
  - magma-cuda110
  - mypy
  - clang-tools
```

</details>

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/pearu/miniconda3/envs/pytorch-cuda-dev:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
_sysroot_linux-64_curr_repodata_hack 3                   ha9d2b57_10    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
binutils                  2.35.1               hdd6e379_1    conda-forge
binutils_impl_linux-64    2.35.1               h193b22a_1    conda-forge
binutils_linux-64         2.35                hc3fd857_29    conda-forge
black                     20.8b1                     py_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
c-compiler                1.1.3                h7f98852_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py39hf3d152e_1    conda-forge
cffi                      1.14.4           py39he32792d_1    conda-forge
clang                     11.0.1               ha770c72_1    conda-forge
clang-11                  11.0.1          default_ha53f305_1    conda-forge
clang-tools               11.0.1          default_ha53f305_1    conda-forge
clangxx                   11.0.1          default_ha53f305_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cmake                     3.19.3               h4547794_0    conda-forge
compilers                 1.1.3                ha770c72_0    conda-forge
cxx-compiler              1.1.3                h4bd325d_0    conda-forge
dataclasses               0.7                pyhb2cacf7_7    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
flake8                    3.8.4                      py_0    conda-forge
fortran-compiler          1.1.3                h1990efc_0    conda-forge
gcc_impl_linux-64         9.3.0               h70c0ae5_18    conda-forge
gcc_linux-64              9.3.0               h7247604_29    conda-forge
gfortran_impl_linux-64    9.3.0               hc4a2995_18    conda-forge
gfortran_linux-64         9.3.0               ha1c937c_29    conda-forge
gxx_impl_linux-64         9.3.0               hd87eabc_18    conda-forge
gxx_linux-64              9.3.0               h0d07fa4_29    conda-forge
hypothesis                6.0.3              pyhd8ed1ab_0    conda-forge
importlib-metadata        3.4.0            py39hf3d152e_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
kernel-headers_linux-64   3.10.0              h77966d4_10    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
libblas                   3.9.0                7_openblas    conda-forge
libcblas                  3.9.0                7_openblas    conda-forge
libclang-cpp11            11.0.1          default_ha53f305_1    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-devel_linux-64     9.3.0               h7864c58_18    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
liblapack                 3.9.0                7_openblas    conda-forge
libllvm11                 11.0.1               hf817b99_0    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-devel_linux-64  9.3.0               hb016644_18    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libuv                     1.40.0               h7f98852_0    conda-forge
llvm-openmp               11.0.1               h4bd325d_0    conda-forge
magma-cuda110             2.5.2                         1    pytorch
mccabe                    0.6.1                      py_1    conda-forge
mkl                       2020.4             h726a3e6_304    conda-forge
mkl-include               2020.4             h726a3e6_304    conda-forge
more-itertools            8.6.0              pyhd8ed1ab_0    conda-forge
mypy                      0.800              pyhd8ed1ab_0    conda-forge
mypy_extensions           0.4.3            py39hf3d152e_3    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
ninja                     1.10.2               h4bd325d_0    conda-forge
numpy                     1.19.5           py39hdbf815f_1    conda-forge
nvcc_linux-64             11.0                h96e36e3_11    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
packaging                 20.8               pyhd3deb0d_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
pip                       21.0               pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py39hf3d152e_4    conda-forge
psutil                    5.8.0            py39h3811e60_1    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pytest                    6.2.1            py39hf3d152e_1    conda-forge
python                    3.9.1           hffdb5ce_3_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pyyaml                    5.4.1            py39h3811e60_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
regex                     2020.11.13       py39h3811e60_1    conda-forge
rhash                     1.4.1                h7f98852_0    conda-forge
sed                       4.8                  he412f7d_0    conda-forge
setuptools                49.6.0           py39hf3d152e_3    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
sysroot_linux-64          2.17                h77966d4_10    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
torch                     1.8.0a0+unknown           dev_0    <develop>
typed-ast                 1.4.2            py39h3811e60_0    conda-forge
typing                    3.7.4.3            pyhd8ed1ab_2    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzdata                    2020f                he74cb21_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : pytorch-cuda-dev
    active env location : /home/pearu/miniconda3/envs/pytorch-cuda-dev
            shell level : 2
       user config file : /home/pearu/.condarc
 populated config files : /home/pearu/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.2=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/pearu/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/pearu/miniconda3/pkgs
                          /home/pearu/.conda/pkgs
       envs directories : /home/pearu/miniconda3/envs
                          /home/pearu/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/4.15.0-132-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by isuruf** [comment]
pytorch requires MKL which requires Intel/LLVM openmp and we force one environment to have only one OpenMP implementation only.

**Comment by pearu** [comment]
The current behaviour leads to 
```
$ python -c 'import torch'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pearu/git/v0dro/pytorch/torch/__init__.py", line 192, in <module>
    from torch._C import *
ImportError: /home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/libgomp.so.1: version `OACC_2.0' not found (required by /home/pearu/git/v0dro/pytorch/torch/lib/libtorch_cpu.so)

$ nm /home/pearu/git/v0dro/pytorch/torch/lib/libtorch_cpu.so | grep OACC
                 w acc_get_device_type@@OACC_2.0
```
This used to work at least a month ago.. and, IIUC, the issue is related to conda environment rather than to a pytorch build.

**Comment by isuruf** [comment]
pytorch wants both GNU and Intel OpenMP?

**Comment by pearu** [comment]
good question, I have not found yet where `acc_get_device_type` sneaks in..

**Comment by pearu** [comment]
It turns out to be a pytorch/cuda issue: one of its components links against `libcupti_static.a` which references `acc_get_device_type@@OACC_2.0`. A fix is to build pytorch with `USE_KINETO=0`.

**Comment by pearu** [comment]
@isuruf, the following script
```
# main.sh
export PACKAGES="compilers"  # TEST 1 SUCCEEDS
export PACKAGES="compilers mkl"  # TEST 1 FAILS
export TESTENV=gomp-test

CONDA_BASE=$(conda info --base)
rm -rf $CONDA_BASE/envs/$TESTENV
source $CONDA_BASE/etc/profile.d/conda.sh
conda create -y -c conda-forge -n $TESTENV $PACKAGES
conda activate $TESTENV

echo "TEST 1"

printf "#include <openacc.h>\nint main() { acc_device_t dev_type = acc_get_device_type(); return acc_get_num_devices(dev_type)+90; }"|gcc -x c -  -Wl,--trace-symbol='acc_get_device_type' -lgomp -o ./test1 ; readelf -s -W ./test1 | grep acc_get
./test1
echo "-> $?"
```
illustrates that having the `mkl` package in conda environment breaks any program using GNU OpenMP, IIUC.

I am uncertain which component of the conda world is causing this.
